# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile

before_install:
- gem update cocoapods
- pod repo update
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/ShapeView.xcworkspace -scheme ShapeView-Example -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO | xcpretty -c
